"""
Quick asset regenerator - generates assetdesa-data.js from assets/assetdesa folder.
Run this after adding new assets to make them appear in the game.
"""
from pathlib import Path
import base64, json, re

ROOT = Path(__file__).resolve().parent
ASSETDESA_DIR = ROOT / "assets" / "assetdesa"
ASSETDESA_DATA_PATH = ROOT / "src" / "assetdesa-data.js"

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".bmp", ".avif", ".apng", ".ico"}
MIME_MAP = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".webp": "image/webp", ".gif": "image/gif", ".svg": "image/svg+xml",
    ".bmp": "image/bmp", ".avif": "image/avif", ".apng": "image/apng",
    ".ico": "image/x-icon",
}


def asset_key_from_path(relative_path):
    stem = relative_path.with_suffix("").as_posix().lower()
    words = re.findall(r"[a-z0-9]+", stem)
    words = ["curve" if w == "curves" else w for w in words if w not in {"set", "tile"}]
    if not words:
        words = ["asset"]
    return words[0] + "".join(w[:1].upper() + w[1:] for w in words[1:])


def main():
    if not ASSETDESA_DIR.exists():
        print(f"ERROR: Folder {ASSETDESA_DIR} tidak ditemukan!")
        return

    assets = []
    used_keys = set()
    for path in sorted(ASSETDESA_DIR.rglob("*"), key=lambda p: p.relative_to(ASSETDESA_DIR).as_posix().lower()):
        if not path.is_file() or path.suffix.lower() not in IMAGE_EXTENSIONS:
            continue
        rel = path.relative_to(ASSETDESA_DIR)
        base_key = asset_key_from_path(rel)
        key = base_key
        suffix = 2
        while key in used_keys:
            key = f"{base_key}{suffix}"
            suffix += 1
        used_keys.add(key)
        assets.append({"key": key, "path": path, "rel": rel})

    print(f"Ditemukan {len(assets)} asset gambar di {ASSETDESA_DIR}")

    data = {}
    for a in assets:
        ext = a["path"].suffix.lower()
        mime = MIME_MAP.get(ext, "image/png")
        raw = a["path"].read_bytes()
        b64 = base64.b64encode(raw).decode("ascii")
        data[a["key"]] = f"data:{mime};base64,{b64}"
        print(f"  + {a['key']} <- {a['rel']}")

    source = "\n".join([
        "// Generated by _generate_assets.py \u2014 base64 embedded data for offline use.",
        "// This file allows index.html to work when opened directly from file explorer.",
        f"window.ASSETDESA_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};",
        "",
    ])

    ASSETDESA_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    ASSETDESA_DATA_PATH.write_text(source, encoding="utf-8")
    print(f"\nBerhasil! {len(data)} asset di-export ke {ASSETDESA_DATA_PATH.name}")
    print(f"File size: {len(source):,} bytes")


if __name__ == "__main__":
    main()
