from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote
import base64
import json
import mimetypes
import re
import sys


ROOT = Path(__file__).resolve().parent
HEALTH_TEXT = "map-editor-save-server-v6"
GENERATED_LAYOUTS_PATH = ROOT / "src" / "generated-layouts.js"
SAVED_LAYOUTS_PATH = ROOT / "src" / "saved-layouts.js"
ASSETDESA_DIR = ROOT / "assets" / "assetdesa"
ASSETDESA_LIVE_PATH = ROOT / "src" / "assetdesa-live.js"
ASSETDESA_DATA_PATH = ROOT / "src" / "assetdesa-data.js"
MAX_LAYOUT_BYTES = 20 * 1024 * 1024
IMAGE_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".webp", ".gif",
    ".svg", ".bmp", ".avif", ".apng", ".ico",
}
MIME_MAP = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".webp": "image/webp", ".gif": "image/gif", ".svg": "image/svg+xml",
    ".bmp": "image/bmp", ".avif": "image/avif", ".apng": "image/apng",
    ".ico": "image/x-icon",
}


def asset_key_from_path(relative_path):
    stem = relative_path.with_suffix("").as_posix().lower()
    words = re.findall(r"[a-z0-9]+", stem)
    words = [
        "curve" if word == "curves" else word
        for word in words
        if word not in {"set", "tile"}
    ]
    if not words:
        words = ["asset"]
    return words[0] + "".join(word[:1].upper() + word[1:] for word in words[1:])


def encoded_asset_src(relative_path):
    return "assets/assetdesa/" + "/".join(quote(part) for part in relative_path.parts)


def file_to_data_uri(file_path):
    ext = file_path.suffix.lower()
    mime = MIME_MAP.get(ext, "image/png")
    data = file_path.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def scan_assetdesa_folder():
    if not ASSETDESA_DIR.exists():
        return []

    assets = []
    used_keys = set()
    for path in sorted(ASSETDESA_DIR.rglob("*"), key=lambda item: item.relative_to(ASSETDESA_DIR).as_posix().lower()):
        if not path.is_file() or path.suffix.lower() not in IMAGE_EXTENSIONS:
            continue

        relative_path = path.relative_to(ASSETDESA_DIR)
        base_key = asset_key_from_path(relative_path)
        key = base_key
        suffix = 2
        while key in used_keys:
            key = f"{base_key}{suffix}"
            suffix += 1
        used_keys.add(key)

        label = relative_path.with_suffix("").as_posix()
        assets.append({
            "key": key,
            "label": label,
            "fileName": relative_path.as_posix(),
            "src": encoded_asset_src(relative_path),
            "fullPath": path,
            "mtime": int(path.stat().st_mtime),
        })

    return assets


def write_assetdesa_live_manifest(assets):
    """Write file-path based manifest for editor (served through HTTP)."""
    data = {a["key"]: a["src"] for a in assets}
    labels = {a["key"]: a["label"] for a in assets}
    files = {a["key"]: a["fileName"] for a in assets}
    source = "\n".join([
        "// Generated by editor-server.py — file paths for editor (HTTP only).",
        f"window.ASSETDESA_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};",
        f"window.ASSETDESA_LABELS = {json.dumps(labels, indent=2, ensure_ascii=False)};",
        f"window.ASSETDESA_FILES = {json.dumps(files, indent=2, ensure_ascii=False)};",
        "",
    ])
    ASSETDESA_LIVE_PATH.parent.mkdir(parents=True, exist_ok=True)
    ASSETDESA_LIVE_PATH.write_text(source, encoding="utf-8", newline="\n")


def write_assetdesa_data_manifest(assets):
    """Write base64-embedded manifest so index.html works when opened directly."""
    print("Generating base64 asset data for offline use...")
    data = {}
    labels = {}
    files = {}
    for a in assets:
        data[a["key"]] = file_to_data_uri(a["fullPath"])
        labels[a["key"]] = a["label"]
        files[a["key"]] = a["fileName"]

    source = "\n".join([
        "// Generated by editor-server.py — base64 embedded data for offline use.",
        "// This file allows index.html to work when opened directly from file explorer.",
        f"window.ASSETDESA_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};",
        f"window.ASSETDESA_LABELS = {json.dumps(labels, indent=2, ensure_ascii=False)};",
        f"window.ASSETDESA_FILES = {json.dumps(files, indent=2, ensure_ascii=False)};",
        "",
    ])
    ASSETDESA_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    ASSETDESA_DATA_PATH.write_text(source, encoding="utf-8", newline="\n")
    size_kb = len(source.encode("utf-8")) / 1024
    print(f"  -> {ASSETDESA_DATA_PATH.name} written ({size_kb:.0f} KB, {len(assets)} assets)")


class EditorRequestHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Cache-Control", "no-store, max-age=0")
        super().end_headers()

    def do_GET(self):
        if self.path == "/__health":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.end_headers()
            self.wfile.write(HEALTH_TEXT.encode("utf-8"))
            return

        if self.path.startswith("/__asset-list"):
            assets = scan_assetdesa_folder()
            write_assetdesa_live_manifest(assets)
            signature = "|".join(f"{a['fileName']}:{a['mtime']}" for a in assets)
            payload = {
                "ok": True,
                "count": len(assets),
                "signature": signature,
                "assets": [
                    {"key": a["key"], "label": a["label"], "fileName": a["fileName"], "src": a["src"]}
                    for a in assets
                ],
            }
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.end_headers()
            self.wfile.write(json.dumps(payload, ensure_ascii=False).encode("utf-8"))
            return

        super().do_GET()

    def do_POST(self):
        if self.path != "/__save-layouts":
            self.send_error(404, "Not found")
            return

        length = int(self.headers.get("Content-Length", "0"))
        if length <= 0 or length > MAX_LAYOUT_BYTES:
            self.send_error(413, "Layout file is empty or too large")
            return

        body = self.rfile.read(length).decode("utf-8")
        body = body.replace("\r\n", "\n").replace("\r", "\n")
        if (
            "window.GENERATED_GAME_LAYOUTS" not in body
            and "window.SAVED_GAME_LAYOUTS" not in body
        ) or '"objects"' not in body:
            self.send_error(400, "Invalid saved layout payload")
            return

        GENERATED_LAYOUTS_PATH.parent.mkdir(parents=True, exist_ok=True)
        GENERATED_LAYOUTS_PATH.write_text(body, encoding="utf-8", newline="\n")
        SAVED_LAYOUTS_PATH.write_text(body, encoding="utf-8", newline="\n")

        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.end_headers()
        response = json.dumps({
            "ok": True,
            "file": "src/generated-layouts.js",
        }).encode("utf-8")
        self.wfile.write(response)


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 4174
    assets = scan_assetdesa_folder()
    write_assetdesa_live_manifest(assets)
    write_assetdesa_data_manifest(assets)
    print(f"Asset manifests updated: {len(assets)} assets")
    server = ThreadingHTTPServer(("127.0.0.1", port), EditorRequestHandler)
    print(f"Map editor server running at http://127.0.0.1:{port}/map-editor.html")
    server.serve_forever()


if __name__ == "__main__":
    main()
